# Generated by Django 5.2.7 on 2025-10-26 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام برند')),
                ('slug', models.SlugField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('short_text', models.TextField(blank=True, max_length=400, null=True, verbose_name='متن خلاصه')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن و توضیخات')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='images/product', verbose_name='تصویر محصول')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('product_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='products.brand', verbose_name='نام برند')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.feature', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی های محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_features',
            field=models.ManyToManyField(through='products.ProductFeature', to='products.feature', verbose_name='ویژگی های محصول'),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product/productgallery', verbose_name='تصویر محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر ',
                'verbose_name_plural': ' تصویر ها',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام گروه')),
                ('image', models.ImageField(upload_to='images/group', verbose_name='تصویر گروه')),
                ('short_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='products.productgroup', verbose_name='والد گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_groups',
            field=models.ManyToManyField(related_name='product_groups', to='products.productgroup', verbose_name='گروه های محصول'),
        ),
        migrations.AddField(
            model_name='feature',
            name='productgroup_feature',
            field=models.ManyToManyField(related_name='productgroup_feature', to='products.productgroup', verbose_name='ویژگی گروه'),
        ),
    ]
