# Generated by Django 5.2.7 on 2025-10-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='', upload_to='images/product', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
