# Generated by Django 5.2.7 on 2025-10-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='previous_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت قبل'),
        ),
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیما نهایی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='متن خلاصه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
