# Generated by Django 5.2.7 on 2025-10-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount_percent_product_previous_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='image',
        ),
    ]
