# Generated by Django 5.2.7 on 2025-10-28 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productfeature_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_title', models.CharField(max_length=100, verbose_name='عنوان مقدار')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.feature', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقدار ویژگی ها',
            },
        ),
        migrations.AddField(
            model_name='productfeature',
            name='filter_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.featurevalue', verbose_name='مقدار فیلتر ویژگی'),
        ),
    ]
