# Generated by Django 5.2.7 on 2025-10-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(True, 'مرد'), (False, 'زن')], default=True, null=True, verbose_name='جنسیت'),
        ),
    ]
